FROM nginx:1.19.6-alpine

LABEL maintainer="luis@ejemplo.com"

RUN  \
  apk update && apk upgrade \
  apk add net-tools git tar wget sudo which curl openssl

# No hara falta usar esta imagen creo


WORKDIR /etc