
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nextjs
  name: nextjs
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: nextjs
  sessionAffinity: None
  type: NodePort
